# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8034b820f04c74cd9bd06e348e3a7e1f358e8b9cc08c427656b9002f2db08d4c2bea1b3812098aee4822acadac4d9cce6a4b539160b16bede4790e2e89cde98d

test:
  secret_key_base: 2224880af2a0ef3c406b73374a17ad64c11dd515f802ebf3d5cbb3f503754cbd1b64d9f6a45fbb2ca0759327a6293121977d272cb432db281782e8d4bb57eb9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
